### ISSUE TITLE
creeper se nastaval

### ISSUE THREAD

**Issue by ondraczsk** [majovec/test#1]
nas oznamil xD

**Comment by majovec** [comment]
Je to kokot stejnak to zverejnim ze @CreeperFace01


Dne 7. 1. 2017 17:17 napsal uživatel "ondraczsk" <notifications@github.com>:

**Comment by ondraczsk** [comment]
xD

**Comment by majovec** [comment]
stejnak anni momentalne bezi na 10 serverech :DDD a on jak buzik nosi divci skin njn buzny musí byt všude

**Comment by Creeperface01** [comment]
Vidím že se bavíte, ale bohužel se nepřidám, jelikož vyhledávám radši zábavu na trošku vyšší úrovni.

**Comment by majovec** [comment]
Jakou hodinu zapinat bw server nebo si hladat jiny divci skin


Dne 7. 1. 2017 8:46 PM napsal uživatel "Creeperface01" <
notifications@github.com>:

**Comment by ondraczsk** [comment]
xD

**Comment by Creeperface01** [comment]
Jinak jak jsem řekl, já nemám čas ztrácet čas s kidy, takže zřejmě jsem vás nenahlásil já.

**Comment by ondraczsk** [comment]
@Creeperface01 https://github.com/github/dmca/blob/master/2017/2017-01-05-MineTox.md

**Comment by majovec** [comment]
Hele Honziku tim kidem myslis sebe jelikoz pokud vim tak slovo kid je
mireno na smrady coz ty jsi a navic stale jsem o par let starsi a btw musel
si to byt ty jelikoz Ondrej @Kvetinac97 na to nema

Dne 7. 1. 2017 21:35 napsal uživatel "ondraczsk" <notifications@github.com>:

**Comment by ondraczsk** [comment]
možná bych měl tuto diskuzi uzavřít xD

**Comment by majovec** [comment]
Ne jen ji nech at se mohu mlavit nad timto kokutkem

Dne 7. 1. 2017 21:41 napsal uživatel "ondraczsk" <notifications@github.com>:

**Comment by Creeperface01** [comment]
Když myslíš, no a už jsem ti to říkal ale klidně to pro tebe udělám a řeknu ti to ještě jednou, slovem kid nemyslím lidi ve věku 0-18, nýbrž lidi kteří se chovají jako ve věku cca 0-13 ale i tak někdo kdo má 13 kid být nemusí.

**Comment by Creeperface01** [comment]
Ale to ty pochopit nemůžeš jelikož sám si... Možná to pochopíš někdy v budoucnosti ale na tvůj věk si tím nejsem úplně jistý no.

**Comment by ondraczsk** [comment]
tahle hádka by nikdy neskončila, closing

**Comment by ondraczsk** [comment]
napište pokud chcete reopen

**Comment by majovec** [comment]
Hele honzo radsi si priprav dalsi zpravu a btw ragnok si vzal na starost
zdileni na vk

Dne 8. 1. 2017 10:33 AM napsal uživatel "ondraczsk" <
notifications@github.com>:

**Comment by Creeperface01** [comment]
Sdílení když už.

**Comment by majovec** [comment]
ZDILENI

Dne 8. 1. 2017 3:22 PM napsal uživatel "Creeperface01" <
notifications@github.com>:

**Comment by majovec** [comment]
ZDILENI

Dne 8. 1. 2017 3:22 PM napsal uživatel "Creeperface01" <
notifications@github.com>:

Sdílení když už.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/majovec/test/issues/1#issuecomment-271154051>, or mute
the thread
